### ISSUE TITLE
Possible Memory Leak on QM9 Dataset

### ISSUE THREAD

**Issue by a-mollahosseini** [GraphPKU/DisGNN#1]
Hello,

I suspect that there might be a memory leak in your code when processing the QM9 dataset. I ran your code on the QM9 dataset and dname of 0, following the same setup and configuration that you reported in your documentation.

During the execution, I noticed that the CPU memory usage steadily increased over the course of a few epochs. Specifically, the memory consumption grew from approximately 5GB to 8GB. This significant increase in memory usage suggests the possibility of a memory leak.

I wanted to ask if you have any ideas potentially where this memory being used. Please let me know if you require any additional information or have any questions.

**Comment by Zian-0427** [comment]
Hello,

Thank you for reaching out!

We have conducted thorough testing of the code, and the CPU memory usage consistently stabilized around 5GB during the initial 15 epochs (It may use less memory, around 4.5GB, at the first epoch, but it will stabilize at 5GB after the first one).

Nevertheless, we have revisited the code in-depth and addressed certain inelegant implementations, particularly in the QM9 file, which could have potentially led to different behaviors among epochs, so you may download the newest version and try again. Also, given that we employed pytorch-lightning as the foundational framework for training and evaluation, we recommend ensuring compatibility by utilizing the version specified in README or a more recent iteration.

Please let me know if this could solve your problem!
